version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.17
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="$HOME/.local/bin:$PATH"
            poetry --version
      - run:
          name: Build
          command: make build
